### ISSUE TITLE
Need HandState to be transported.

### ISSUE THREAD

**Issue by dr-ratio** [stimulant/MS-Cube-SDK#16]
Perhaps this could just accompany the Bodies data?  Or it could be a new category besides Bodies/Depth.  Since we have to do our own gesture recognitions, we need this data IE Open/Closed/Lasso state, for left and right hands.  The High/Low Confidence rating should probably also accompany it.
EDIT: After feedback, our target experience just changed and this has become Very High priority as we will need to know when hands are closed ASAP.  Thanks!

**Comment by joelpryde** [comment]
Went ahead and added this as it is high pri.  Only the Unity sample currently reads and displays these values (will be fixing the other samples shortly).  You will also need to rebuild the KinectTransport app.  I didn't have time to add confidence rating.  Please add another bug with a different priority if you guys still need that after trying this out.

The available hand states are:

public enum HandState
{
    HandState_Unknown   = 0,
    HandState_NotTracked    = 1,
    HandState_Open  = 2,
    HandState_Closed    = 3,
    HandState_Lasso = 4
};
