### ISSUE TITLE
Bodies position do not match depth

### ISSUE THREAD

**Issue by mflux** [stimulant/MS-Cube-SDK#7]
On branch kinecttransport_send_fulldepth

The bodies no longer match the position of depth image.

![bodiespositionoff](https://cloud.githubusercontent.com/assets/1041360/5464188/cda4a55c-8539-11e4-995e-86ade795e9fd.png)

Confirmed on both Cinder sample and P5 sample

**Comment by joelpryde** [comment]
The samples just happen to overlay these two types of data but unfortunately it is not possible to overlay them as the data is in two different coordinate spaces (and one is in 3D and one in 2D).  The Kinect 2 SDK has methods for translating between these two coordinate spaces but I don't have access to them without the Kinect 2 SDK (which the cinder and JS samples don't have access to).
